on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Setup Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: 'npm install and build'
      run: |
        npm install
      # npx quasar build
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with:
        app-name: test-nodejs
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        package: './dist/spa'